line = input()
line = line.replace('a','')
line = line.replace('e','')
line = line.replace('i','')
line = line.replace('o','')
line = line.replace('u','')
line = line.replace('y','')
line = line.replace('A','')
line = line.replace('E','')
line = line.replace('I','')
line = line.replace('O','')
line = line.replace('U','')
line = line.replace('Y','')
print(line)